FROM ubuntu:rolling

RUN apt update && apt install -y pkg-config g++ libsdl2-dev libsdl2-image-dev libboost-program-options-dev && rm -rf /var/lib/apt/lists

WORKDIR /usr/src/app

COPY . .

RUN make -j4
