#ifndef __OPERATIONS_H__
#define __OPERATIONS_H__

#include "BrightnessAdjustment.h"
#include "ContrastAdjustment.h"
#include "Negative.h"
#include "HorizontalFlip.h"
#include "VerticalFlip.h"
#include "DiagonalFlip.h"
#include "Resize.h"
#include "AlphaTrimmedMeanFilter.h"
#include "ContraharmonicMeanFilter.h"
#include "MeanSquareError.h"
#include "PeakMeanSquareError.h"
#include "SignalToNoiseRatio.h"
#include "PeakSignalToNoiseRatio.h"
#include "MaxDifference.h"
#include "RosenfeldOperator.h"
#include "LowPassFilter.h"
#include "RaleighFPDF.h"
#include "Erosion.h"
#include "Dilation.h"
#include "Opening.h"
#include "Closing.h"
#include "HMT.h"
#include "RegionGrowing.h"
#include "ConvertToGrayscale.h"
#include "Binarize.h"
#include "M5.h"

#endif
